- name: FoundryVTT AutoPublish
  uses: Varriount/fvtt-autopublish@v2.0.2

  - name: Publish Module to FoundryVTT Website
    uses: Varriount/fvtt-autopublish@latest
    with:
      username: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
      password: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
      module-id: ${{ secrets.FOUNDRY_ADMIN_MODULE_ID }}
      manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_NAME }}/module.json
      manifest-file: ${{ env.MANIFEST_FILE_PATH }}
