response = await fetch("https://api.foundryvtt.com/_api/packages/release_version/", {
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'fvttp_des9QKlIcPmU2ryTBYCUqRp3'
  },
  method: "POST",
  body: JSON.stringify({
    "id": "example-module",
    "dry-run": true,
    "release": {
      "version": "2.0",
      "manifest": "https://github.com/Pedigruu/WFRP4e-Skaven/releases/download/2.0/module.json",
      "notes": "https://github.com/Pedigruu/WFRP4e-Skaven/releases/tag/2.0",
      "compatibility": {
        "minimum": "12",
        "verified": "12",
        "maximum": ""
      }
    }
  })
});
response_data = await response.json()
